language: python
sudo: required
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
before_install:
  - git clone --depth=1 https://github.com/behdad/fonttools.git
  - git clone --depth=1 https://github.com/typesupply/fontMath.git
  - git clone --depth=1 https://github.com/unified-font-object/ufoLib.git
  - git clone --depth=1 https://github.com/typesupply/defcon.git
install:
  - cd fonttools; python setup.py install; cd ..
  - cd fontMath; python setup.py install; cd ..
  - cd ufoLib; python setup.py install; cd ..
  - cd defcon; python setup.py install; cd ..
  - python setup.py install
script:
  - python -c "import fontTools"
  - python -c "import fontMath"
  - python -c "import ufoLib"
  - python -c "import defcon"
  - python Lib/fontParts/nonelab/test.py
